### ISSUE TITLE
Suggestion: Make volafile.tk a safe place for all

### ISSUE THREAD

**Issue by NestorVola** [Volafile/volafile-bugs#101]
Dear Lain,

I have noticed at times that files are uploaded to volafile.tk that contain viruses.  Mods then have to download them to verify, often downloading them, then uploading to a site such as VirusTotal, considering most moderators are neckbeards who run GNU/Linux (And demand that it be referred to as such).  Volafile.tk should automatically upload all files to VirusTotal, and delete them if more than a certain threshold of scanners tag it as malicious, for example 75%.  VirusTotal currently has a limit of 65MB (Previously 25MB), so every file greater than that size would need to be chopped up into 65MB chunks before uploading them to VirusTotal.  I know what you are probably thinking: "NestorVola, what if the virus is placed strategically at a 65MB barrier, so that its signature is split at that point, and the entire signature is never sent to VirusTotal."  The solution is simple.  Every file should be split up and uploaded twice.  In one run, all chunks are 65 MB, in the other run, chunk0 is 32.5MB.  Then each chunk is uploaded to VirusTotal, and checked for safety.  This would greatly enhance the security of Volafile.tk, and should have only a minor impact on performance.

Love,
NestorVola

xoxo hugs and kisses

P.S. BsdFggt sagte mir, dass in Latin Amerika xoxo "Muschi" bedeutet.  Ich meinte "hugs and kisses," _nicht_ "Muschi."

**Comment by laino** [comment]
We have some basic malware scanning using clamav by now
