### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by stixx** [Volafile/volafile-bugs#104]
- [x] Music player button is gone in chat (Lain: should be fix'd)

- [x] Sometimes when concurrentuploads in another room is pushed to 20 ( even though you're not actually uploading 20 files) other files in other rooms don't push trough. (Lain: This is not supported)

- [x] when you speak as '/me' your username also adapts but this can cause lagging and sometimes it takes a long time before it's rendered

**Comment by laino** [comment]
see my notes in the OP
