### ISSUE TITLE
Disabling upload in a room does not cancel uploads.

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#107]
User1 starts uploading a file.
Mod1 disables uploading in room during the upload of User1's file.
User1's file appears in the filebin even though it shouldn't have.

**Comment by laino** [comment]
There's now a second test on the upload server once the file has completed uploading, so this shouldn't happen (there's still some possible race conditions there though, so it might still happen if the file is uploaded with 1-2 seconds of the room being disabled).
