### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by lg188** [Volafile/volafile-bugs#120]
Currently when someone upload something and you're not at the top, the screen scrolls down.
Replace this behaviour with a statical view when no on the top.
If it's a problem with the last uploads dissapearing, just scroll up I guess.

**Comment by laino** [comment]
I was hoping the movement on an users screen would draw attention to the fact that something new was uploaded. Maybe I'll fix the scroll position and make the filebin flash or something.

**Comment by laino** [comment]
doesn't scroll anymore and shows a notification about new files instead
