### ISSUE TITLE
Feature Request: Resume/Drop Interrupted Uploads

### ISSUE THREAD

**Issue by volaTRM** [Volafile/volafile-bugs#122]
Is it possible to distinguish whether a file has finished uploading or has been dropped due to a connection error? Downloaded 1.3GB of a 1.8GB file, uploader responded and said they were not informed that the upload was incomplete.

Would it be possible to either note that a file has not uploaded entirely and give the option to continue uploading if the connection is upset?

Another possible solution would be to simply drop any file that hasn't completely uploaded.

**Comment by laino** [comment]
Volafile will automatically resumed interrupted uploads. And you will not see a file before it was completely uploaded.

The problem was likely a connection error during download, on your end.
