### ISSUE TITLE
[Improvement] Needing to click "File Filter" before I can click on icons to filter files is annoying and unnecessary

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#123]
Having to click the thing that says "Filter Files" in order to view the filters I can click on to filter files creates a completely  unnecessary step a person has to go through in order to filter files. I see no use for having to click on this before I can click on music/image/document icons to filter for those filetypes.

Please revert this to the way vola ui used to be where it always showed the file filtering options.

**Comment by laino** [comment]
Before I changed it that way users always got confused what the buttons actually do. By labeling them that way you'll have to know what you want to do before you even click it.
