### ISSUE TITLE
Allow loli on the site

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#124]
loli is qt, never hurt anyone, and according to a court ruling in Germany, fictional novels, drawings, and cartoons do not fulfill the conditions of being child pornography because there is no real child "agent" being abused in them.

http://www.hrr-strafrecht.de/hrr/1/13/1-8-13.php

Meanwhile I am not aware of any German court ruling that posession or distribution of this content is actually illegal.

Also the Netherlands do not give a single fuck about loli and wouldn't care that you allow it.

**Comment by laino** [comment]
no
