### ISSUE TITLE
Obscure IP addresses from mods.

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#125]
Instead of showing every user's real ip address, create a unique id for each user visible only to mods. They can use this id to identify individuals in the same way they currently use IP addresses.

IP addresses are not necessary for mods to perform their functions. To many people, an IP address is very sensitive information. You are not known for choosing mods based on trustworthiness. Because you can not select trustworthy moderators, it is necessary that you remove moderators from the trust equation. Do not give them this sensitive data.

**Comment by Robertcop** [comment]
i agree with this. please listen to anon3000.

**Comment by indrakaw** [comment]
Vote-up for anon3k.

**Comment by SkaarjK** [comment]
I, too, agree with this.

**Comment by dongmaster** [comment]
++

**Comment by PhearTheCeal** [comment]
Wow, it's like none of you thought about how this would be implemented. Volafile servers would have to store everyone's ip and associate it with an ID. This obviously breaks the terms of the privacy policy.

**Comment by redrifle** [comment]
I think you could maybe run the IPs through a caesar cipher with a random shift value (generated by a RNG)?
It'd be very barebones but I think it'd work and still be easier and possibly faster than the other method.
If I'm retarded let me know.

**Comment by Robertcop** [comment]
this needs to be implemented. not just because of rogue. what anon said makes a lot of sense.

**Comment by bastardsandcheats** [comment]
> To many people, an IP address is very sensitive information
> To paranoid people
> This is a silly idea and not needed at all

**Comment by laino** [comment]
rogue has been removed
