### ISSUE TITLE
bug report: dl3 is rekt because dl4 is rekt

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#127]
I just noticed something:
dl4 will reset upload connections after exactly 120 seconds. Seems like a configuration error, hence I declare dl4 to be rekt.
**_Result: Cannot upload "big" stuff to dl4**_

This in turn cause me - and probably other people? - to overuse dl3.
I'm doing my dump, and I complained before that every second connection gets reset. Turns out those were the connections to dl4...
This caused all files to be uploaded to dl3 eventually. Now, that dump seems somewhat popular if the 20+ more people than usual in the room are any indication... Probably downloading Terabytes worth of the game.
**_Result: dl3 is rekt speed-wise.**_

STR:
- Upload something large to dl4
- Wait 120s
- See connection reset by remote host

Expected:
- Upload succeeds

Please fix dl4 Mr @laino

**Comment by RealDolos** [comment]
shit still rekt @laino

**Comment by RealDolos** [comment]
@laino fscking REKT
![dl4 is fucking rekt](https://cloud.githubusercontent.com/assets/9981466/10321053/f1ac3c38-6c76-11e5-9258-83da88252b85.png)

**Comment by RealDolos** [comment]
There is an encrypted TLS 1.2. alert just before the RST, probably close_notify, originating from the server, meaning the server actually closed the connection unilaterally. Being an encrypted alert and the stack does not throw any TLS errors upon receiving it, it cannot be a MITM hop resetting the connection either, but the actual TLS endpoint on the server. So Mr @laino fix your shit.

**Comment by dongmaster** [comment]
Can confirm that uploads die after 120 seconds.
I emailed you video proof of it, @laino

**Comment by RealDolos** [comment]
https://dl4.volafile.io/get/iNDTPptZOg-UK/LAIN%20FIX%20DL4.mp4 <topkuk

**Comment by RealDolos** [comment]
@laino something still tells me this is a configuration error in the wider sense:
https://nodejs.org/api/http.html#http_server_timeout

> Default: 120000 msec

Coincidence?

**Comment by Robertcop** [comment]
fix this server and any others dear liano

**Comment by Robertcop** [comment]
any changes?

**Comment by RealDolos** [comment]
@Robertcop https://github.com/RealDolos/volaupload supports the resumption hack/protocol nao... Then again, you're roboCop...

**Comment by Robertcop** [comment]
that doesn't help and you know it

**Comment by laino** [comment]
Some changes have gone live the past few days, are there any _recently_ uploaded corrupt files?
