### ISSUE TITLE
Clicking an image while in gallery mode opens two tabs.

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#128]
**Issue**
Clicking an image in gallery mode opens two tabs.

**How to reproduce**
1) Click an image in the file list to bring up the gallery mode.
2) Click the image.

**What should happen**
1 (one) browser tab should open.

**What happens**
2 (two) browser tabs open.

**Video demonstration**
https://my.mixtape.moe/uaoiqy.mp4

**Comment by Robertcop** [comment]
i second the motion for it to be fixed
PLS

**Comment by dongmaster** [comment]
I wrote a script to fix this issue: https://github.com/dongmaster/volafile-scripts/blob/master/volafile-gallery-fix.user.js

Click the Raw button to install the script.

**Comment by laino** [comment]
fixed
