### ISSUE TITLE
Servers corrupt files again

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#129]
I've seen quite a few uploads recently being corrupted by many different uploaders.
File sizes vary.
Since TLS protects against regular in-transit data corruption, it seems more than likely that the upload end point corrupts the data, or even worse a hardware failure.

@laino pls fix

Pls also make available some kind of checksum for uploads via some API. You're md5'ing the files anyway for the blacklist feature. Providing that hash would suffice.

**Comment by RealDolos** [comment]
To quote the movies room:

> Adonis:so many corrupted files. i want them all

**Comment by Robertcop** [comment]
i too have seen MY OWN uploads ruined and CRC MD5 mismtach. i will upload via volaupload and then download a few. all of them do not match the md5. whether its a video file or an archived file! come on lain dont you see? something is really wrong here. please do something man!

**Comment by laino** [comment]
I suspect the upload resuming being broken actually. How does volaupload handle it?

**Comment by RealDolos** [comment]
@laino It is kinda broken in the browser FWIK, i.e. there are lots of people complaining about resets.
The resumption stuff of volaupload.py mostly works, for me at least, but sometimes the file gets corrupted. I seen a bunch of corrupted files uploaded by people who are clearly not using volaupload.py, and some are even small enough (only a couple of MB) that I'm not even entirely sure if those were resume-uploaded at all.
The volaupload.py code is actually volapi code and is here: https://github.com/RealDolos/volapi/blob/master/volapi/volapi.py#L673-L710

**Comment by RealDolos** [comment]
@laino, post upload resume code xD

> inb4 open source is bad.

**Comment by GuillaumeBailey** [comment]
WORKAROUND: Use Multipar (http://multipar.eu/) to generate parity files to recover the files. Seems like 0.1% parity would be enough. The attached files are a sort of case-study for the recovery.

![the walking dead s06e04 720p hdtv x264-0sec mkv - multipar - 2 ready to repair](https://cloud.githubusercontent.com/assets/1377360/10898244/6fcfc3ee-817d-11e5-83f7-22a08f167513.PNG)
![the walking dead s06e04 720p hdtv x264-0sec mkv - multipar - 3 succeeded](https://cloud.githubusercontent.com/assets/1377360/10898245/6fd118fc-817d-11e5-80e3-a42d5a833eef.PNG)
![the walking dead s06e04 720p hdtv x264-0sec mkv - multipar - 4 corrupt original par and repair blocks all ok](https://cloud.githubusercontent.com/assets/1377360/10898247/6fd1b4ba-817d-11e5-9dc2-0526469f4e5e.PNG)
![multipar setup example](https://cloud.githubusercontent.com/assets/1377360/10898248/6fd22df0-817d-11e5-86fe-fbdb81b5fb6d.PNG)
![the walking dead s06e04 720p hdtv x264-0sec mkv - multipar - 1 need 8 more blocks](https://cloud.githubusercontent.com/assets/1377360/10898246/6fd1aa7e-817d-11e5-8ddf-0686a780510b.PNG)

**Comment by laino** [comment]
@RealDolos the code handling uploads in Volafile is thousands of lines, but resuming is a well-tested feature.

Does it only happen on specific servers?

**Comment by RealDolos** [comment]
@laino Well tested in "it never really works"? There have been countless people complaining that resuming will often just reset the download and stuff like that, although the corruption issues seem more recent.
I've seen the resets some few times myself, where the uploadState endpoint would simply not provide a receivedBytes mid-download.

I _think_ I've seen it on both servers, but recently it was dl4 most of the time/all of the time. It is actually somewhat hard to tell when it happens since I do not usually download and re-check my own uploads.

If only one server was affected I'd guess hardware failure. But this way, it seems more likely that the volafile upload code is to blame. Since volaupload works most of the time, and since this happens with regular in-browser downloads as well, I think volafile is to blame.

**Comment by laino** [comment]
```
If only one server was affected I'd guess hardware failure. But this way, it seems more likely that the volafile upload code is to blame.
```

More likely it's timeouts. If the client takes to long to ask for upload status, the server will have removed the partial file already.

**Comment by RealDolos** [comment]
I was talking about the corruption issues. The timeout issues, maybe, but not always it seems. But I don't really care about the timeout issues anyway.

**Comment by RealDolos** [comment]
Adonis in BEEPi just provided corrupted uploads (by some n00b user, so probably in-browser uploads) that show dl3 and dl4 have corrupted files.

**Comment by RealDolos** [comment]
Here is a pic of files uploaded to (by volanoob in TV) then downloaded from volafile and then checked against some torrent checksums, courtesy of Adonis. Massive corruption is obvious, even despite the torrent program tentatively marking whole blocks as mismatched when only a few bits or bytes were corrupted in that block.

_removed_

**Comment by RealDolos** [comment]
I uploaded something, which got corrupted, so I diffed the files.
I looked at where the file got first corrupted and then looked data in that location:
The data at offset 643383129 in the original file is present in the corrupted file at 643383129 as it should, but again repeated from 643514201 onwards, as it should not.
If you diff that you get `643514201  - 643383129 = 131072` or `(1<<17)` or `128KiB`, which does not look much like a coincidence.

So it seems that when resuming the file on the server gets a seek 128KiB past where it is supposed to be resumed sometimes. This does not happen always, tho. Could be some kind of race? Or stale data written too late?

I checked with one of Oneroi's corrupt files in TV and same thing: Data is repeated after `131072` aka `128KiB`.

**Comment by RealDolos** [comment]
To give a shitty and confusing example, let's assume this is a file of multiple virtual 128KiB blocks. It would normally look like this:
`ÁBCDEFGHIJK`
When corrupted it will look something like this:
`ABCDDEFGIJK`
It still has the same size, but `D` is there twice, moving `DEFG` 128KiB out of place, eliminating `H` somehow.

I would think something like this happens:
1. connection: `ABC` (or `ABCD`) and connection reset after 120s
2. connection: `DDEFGH` (or `DEFGH`) and connection reset after 120s
3. connection: `IJK`, where I as at the correct offset again, overwriting previous H

**Comment by laino** [comment]
Thank you. It'll give me something to have a look at.

**Comment by RealDolos** [comment]
> made some small changes, pls tell whether it fixed file corruptions

nice, @laino . Still, can I haz md5 for an upload from some API so I can easily check it against source md5 and by that detect corruptions without actually downloading files? Gib md5 (or whatever checksum) pls

**Comment by laino** [comment]
I'll probably exposes some checksums via an API endpoint soon

**Comment by RealDolos** [comment]
@laino new corrupt file(s) in PCT3eD at least <removed>

**Comment by Robertcop** [comment]
@laino files are once again getting corrupted lain. your patch job or whatever wasn't enough. please help us obeonelaino. you're our only hope.

**Comment by Robertcop** [comment]
both in [removed] and [removed]
not sure if it's server wide.

**Comment by laino** [comment]
I made some changes, let's see if it's still happening

**Comment by MyPrivateFilesGoHere** [comment]
files are still corrupted

**Comment by Robertcop** [comment]
lain help us :-1:

**Comment by laino** [comment]
fix'd

**Comment by Robertcop** [comment]
this is not fixed. time to reopen

**Comment by Robertcop** [comment]
[removed]
has hash f12e50eebfadca6492382738de7c0e55
[removed]
 has hash f24df1a733a8c5fa6b228f304a7ff940

more proof later maybe!:-1::-1::-1::-1::-1::-1:

**Comment by laino** [comment]
Should be resolved with new download code. Also checksums can now be retrieved.
