### ISSUE TITLE
Uploading is impossible because "No storage servers found!" and logging in is impossible

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#130]
Trying to log in returns this error message: "
Error: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.,Error: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.,Error: Error: EXECABORT Transaction discarded because of previous errors."

@laino

**Comment by RealDolos** [comment]
@dongmaster my error report is better, why you do this to me?

**Comment by dongmaster** [comment]
>my error report is better
>doesn't summarize the problem in the title of the issue

läl

**Comment by RealDolos** [comment]
News at 9, volafile.io rekt again, users swarm in to thank emperor @laino
