### ISSUE TITLE
At first I was like... cuck... but then I redis

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#131]
> Error: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.,Error: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.,Error: Error: EXECABORT Transaction discarded because of previous errors.

Do you even login? And if you do, why does it pass through redis errors?

**Comment by laino** [comment]
Thank you. Where exactly was the error passed through?

**Comment by RealDolos** [comment]
When attempting to login in the Error box that you normally only get to see when you mistyped your password.
