### ISSUE TITLE
Users disappear

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#135]
This usually happens when MercWMouth enters a room and sees some expressed opinions he does not like. Usually users just disappear shortly thereafter, in particular a user named NSF001

**Comment by Robertcop** [comment]
i too can atest to this issue. sometimes it's user NSF001 OR unregistered unknown white names whose opinions don't fall in line with MercWMouth feels threatened by truthful opinions. this bug needs fixing not closing or ignore lain

**Comment by RealDolos** [comment]
Can reconfirm, happened in the last 24h multiple times
