### ISSUE TITLE
Account passwords stop working

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#138]
Not for me yet, fortunately, but LewdBot stopped for Dong, kreg's account is rekt, Xiao cannot log in.
DATA CORRUPTION!!!!!1!

**Comment by RealDolos** [comment]
Apparently kreg was just shitposting or something.
But Daniel said one of his accounts is broken

**Comment by dongmaster** [comment]
Can confirm. My LewdBot account is broken. I can't log in anymore.
I haven't changed the password for the account recently.

**Comment by RealDolos** [comment]
> kreg:session cookie saved
> kreg:but I can't log in

**Comment by RealDolos** [comment]
> TheJIDF:Ohh wow I CANT LOG INTO MRSHLOMO
> TheJIDF:FUCKING SHIY

**Comment by RealDolos** [comment]
> TheJIDF:Eow not even JewMobile. Thats my favorite to post shopping pics from
> TheJIDF:FUCKING @laino

**Comment by RealDolos** [comment]
>TheJIDF:Did not change pass

So BITROT IN THE DB! PANIC!!!

**Comment by dongmaster** [comment]
List of accounts that have been fucked (read: You can not login to these accounts, even with the correct password), to my knowledge:
1. Xiao
2. dad
3. LewdBot
4. kreg
5. JewMobile
6. MrShlomo
7. DavidM
8. Elyssium
9. random1
10. Lmmortal

**Comment by laino** [comment]
Mhh. Looks like I'll have to check for some bad RAM.

**Comment by laino** [comment]
Think it was an issue with some data being saved as strings, which started producing different strings once parsed again because unicode/unicode parsers changed somewhere.

Anyways we have password reset now too.
