### ISSUE TITLE
cloudflared dl servers give 403 errors

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#140]
When I queued up some downloads, the now cloudflared download servers decided to reject half the requests with a 403 response.
This suggests that some "anti DDoS" shit is turned up too far. I mean, c'mon?! Your buttbuddy merc is telling people all the time to just use "DownThemAll to download rooms" and that is what I did.

Almost verbatim:

```
Request Headers

GET https://dl3.volafile.net/get/Z0V4PyJQOg-R/484128jennyhofmann%20(7).jpg
Host: dl3.volafile.net
User-Agent: Mozilla/5.0 (Penix64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/metalink4+xml;q=0.9,application/metalink+xml;q=0.8
Accept-Language: en-US;q=0.7,en;q=0.3
DNT: 1
Want-Digest: SHA256,SHA512,SHA;q=0.4,SHA1;q=0.4,MD5;q=0.3
Cookie: __cfduid=someshithash
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

```
Response Headers

403 Forbidden
Server: cloudflare-nginx
Date: Fri, 19 Feb 2016 06:39:43 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: max-age=15
Expires: Fri, 19 Feb 2016 06:39:58 GMT
X-Frame-Options: SAMEORIGIN
CF-RAY: 276ff9e909182774-FRA
```

Retrying those things later will succeed.

@laino pls fix your cloudflare settings

**Comment by laino** [comment]
Don't use more than one part per file. Especially with smaller files.

**Comment by RealDolos** [comment]
I do not, I have a limit of 1 segment per download already, and 4 downloads concurrent, pls

**Comment by RealDolos** [comment]
The issue is even present with one segment per download and one download concurrent btw. Just download a bunch of files and the "anti DDoS" protection will kick in.

**Comment by RealDolos** [comment]
> Chaos:HTTP load failed with status 403. Load of media resource https://dl3.volafile.org/asset/VckWPpTEOg8x/video_thumb failed.
> Chaos:Load denied by X-Frame-Options:
