### ISSUE TITLE
Use X-Frame-Options already

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#144]
https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

Liquid linked some cam sluts website that literally iframe embeds Renegade a while back. This is total shit ofc not only because it makes Renegade huge but also because when people navigate the irframe gets reloaded...

To avoid shit like that, make volafile non-iframe embeddable (in proper browsers at least) via X-Frame-Options

**Comment by laino** [comment]
Added some simple framekiller script instead
