### ISSUE TITLE
Abusive moderator behavior

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#145]
Dearest, most gracious and most sexually desirable @laino,

I come to a room and there is literally a wall of text mostly purple.
Look at it, mostly merc. Look at what is posted besides that: mostly a user named "Deadpool", so merc decided to fucken talk to himself (which is a concern in itself). For hours on end. Badgering Liquid mostly (I wasn't there, so this wasn't his regular dolos-rage). The screenshot shows just the most tiny fraction of what happened. And yes, that is the real `deadpool` not some `deadpooi` fake.

![hi-me-its-me](https://cloud.githubusercontent.com/assets/9981466/14864079/a37b8d10-0cb8-11e6-98b8-0ff3733fe560.png)

The room owner, our dear old cucklord supreme Liquid, has asked merc to stfu and get out repeatedly, BasedAnon commented about merc being an ass and @dongmaster  did too, at the very least.

I'm no stranger to shitposting, but talking to yourself on a massive scale for the sake of spam, after you had been **uninvited** from a private room, that's usually a reason to **mute** people, not _"reward"_ them with a modship.

I'd therefore make the following suggestions:
1. Allow mods to mute other mods at least on a per room basis. If this leads to fighting, you will pretty surely be made aware of it pretty fast and as benevolent dictator for life of volafile make a binding decision.
2. Make it clear that, like this spammy behavior is not acceptable from users, it is also not acceptable in particular from any mod.
3. Make it clear that mods are hold to a slightly higher standard than random whitenames, in that mods are supposed to keep the site running instead of actively shitting it up to the point the chat effectively becomes unusable.

**Comment by RealDolos** [comment]
> MercWMouth:for the same reason that i'm showing flexibility with the one airhead and letting him make a post every 180minutes,
> MercWMouth:I'm showing flexibility with Liquid by not nuking this room due to its content.

Just to get this straight, instead of fighting spam, merc is spamming himself and also threatening to nuke Liquid's room.

**Comment by RealDolos** [comment]
And once he learns I'm in that room too, this happens:

> MercWMouth:>implying I'm not flexibile enough not to take out the 'No Mercy Rea­lDo­los' evasion-proof ban tool

**Comment by dongmaster** [comment]
I've tried to make him leave a particular room, however, he has not complied with my orders/requests.
No one wants him in the room, yet he still goes in there.

**Comment by RealDolos** [comment]
> 21:11:20 | MercWMouth:Deadpool: Isn't that right?
> 21:11:25 | Deadpool:yeah, pretty much

**Comment by RealDolos** [comment]
> MercWMouth:I don't think it should go unmentioned that his track record includes _two_ separate tantrums the first which lasted 14hours and the second which lobotomized the email servers which by themselves are why he's supposed to remain banned until autumn...

**Comment by RealDolos** [comment]
And it seems he leaked one of my IPs again. Completely not retaliatory but an honest mistake I'm sure.

**Comment by RealDolos** [comment]
> MercWMouth:reaIdoIos: See? I'm generous twoards both of you. Be grateful.

**Comment by RealDolos** [comment]
> 21:31:42 | MercWMouth:Liquid: look, I'm not going to nuke this. I've made that much clear--
> 21:31:51 | MercWMouth:but, goddamn. you're coming close to that line with this crap.

**Comment by RealDolos** [comment]
The IP thing was this btw:

> 21:18:19 | RealArke:MercWMouth why are you uploading user ip's
> 21:18:36 | MercWMouth:lol. my bad. ♥
> 21:18:41 | MercWMouth:anyway, not a big deal in his case.
> 21:18:55 | MercWMouth:he keeps switching em or else he'd have been thrown out permanently a long time ago
> 21:19:35 | MercWMouth:RealArke: But I swear to god he had better not been implying what I thought he might be implying at first glance...
> 21:19:37 | MercWMouth:We clear?
> 21:21:00 | TheBroChris:oh, **did murc leak my IP again**, RealArke?
> 21:21:09 | RealArke:ya
> 21:21:09 | MercWMouth:TheBroChris: **Yep!**

**Comment by RealDolos** [comment]
> 21:45:27 | Liquid:TheBroChris he went full autism again and and deceided to spam 200+ images, i reported the room/person over 9 hours ago
> 21:45:38 | Liquid:Metc hasn't left since

**Comment by RealDolos** [comment]
> Liquid:All I asked Merc to do was temp ban the spammer so the filespam would stop

**Comment by RealDolos** [comment]
> _MercWMouth throws something shiny in Liquid's periphiral vision_

**Comment by FilthyLiquid** [comment]
I'll clear some stuff up as the beginning of all this is missing (and in it's own-right stupid). 
I was in my room, and somebody comes in and posts some advertising images (he was trying to sell some videos). I quickly tell him to GTFO and delete his files, he did not like this and decides to spam the same images over 200 times, I report the the room to the mods so that they can issue a a temp ban that would stop the spam in my room. This is where it should have ended.
Enter MercWMouth. MercWMouth decides to try and come to sort of arrangement with the spammer that would allow him to keep his uploads in my room despite me saying no several times already, as I already stated, I did not want his files in my room, so I quickly deleted the images the advertiser was posting. MercWMouth did not like this for some reason and even went as far as removing the room ownership from me (admittedly, I got it back pretty quickly) which made no sense at all. Despite me still resisting allowing advertising in my room, MercWMouth continues to try and dispute this, even going as far as saying "I am the mod and public relations manger, do as I say or else". Spammer continues posting and I continue deleting, this seems to irritate MercWMouth further, so he creates a new room for the spammer to post his files where I can't delete them. MercWMouth bargains with the spammer that would allow him to post his advertising, despite me saying no 100000x over at this point. Now instead of me having control of the advertising in my room, MercWMouth essentially just ended up teaching him a new way of spamming my room by linking the files from the other room. This issue could have been avoided if a real moderator was online at the time (BasedAnon got there a little later, but thank you for being on my side), instead this has turned into a 10 hour shitstorm.

**Comment by dongmaster** [comment]
That is clearly how you handle a situation like that.
Good job, MercWMouth.

**Comment by RealDolos** [comment]
![screenshot-volafile io 2016-04-28 07-15-05](https://cloud.githubusercontent.com/assets/9981466/14878321/1624a828-0d23-11e6-8760-4cd138ca0a4c.png)
:100:

**Comment by RealDolos** [comment]
Shoty screens courtesy of @FilthyLiquid 

![screenshot-volafile io 2016-04-28 07-05-18](https://cloud.githubusercontent.com/assets/9981466/14878360/61b5a09e-0d23-11e6-94ca-0aa3c0b717f5.png)
![screenshot-volafile io 2016-04-28 06-59-45](https://cloud.githubusercontent.com/assets/9981466/14878361/61b67942-0d23-11e6-9076-a4ad31de342c.png)
![screenshot-volafile io 2016-04-28 07-01-01](https://cloud.githubusercontent.com/assets/9981466/14878362/61cb7388-0d23-11e6-930b-169e164d7ff1.png)
![screenshot-volafile io 2016-04-28 07-04-36](https://cloud.githubusercontent.com/assets/9981466/14878363/61cc7b16-0d23-11e6-88e0-bb24f817d6e3.png)
![screenshot-volafile io 2016-04-28 07-02-39](https://cloud.githubusercontent.com/assets/9981466/14878364/61e154d2-0d23-11e6-8121-fb7739bfa551.png)

**Comment by RealDolos** [comment]
Oh, and can confirm that @FilthyLiquid  was told by real mods not to remove problem files himself but report it to a mod. Preferably not using the Report feature as it will only draw the attention of the merc.
Yes @laino, mods tell your users to not use the Report button now and use other means of communication just to avoid triggering the merc into full retard mode.

**Comment by RealDolos** [comment]
> MercWMouth:TheBroChris: Yes, and TheJIDF also has to rever the ban I just issued on your uploads. See all the work you put him through?

**Comment by RealDolos** [comment]
> System:You are muted. This ban expires in 59 minutes 31 seconds. Reason: dear thejidf, please unban realdolos. oh, and don't plan on leaving anytime soon. ;) The drama's about to kickup a notch! :D

**Comment by RealDolos** [comment]
> MercWMouth:rea­ldolos: cmon, start up some drama.

**Comment by RealDolos** [comment]
> 11:37:36 | MercWMouth:Hey, Merc!
> 11:37:39 | merc:yeah?
> 11:37:43 | MercWMouth:Stop using AVI!
> 11:37:47 | TheBroChris:stop the "hurrdurr, I was only pretending"
> 11:37:49 | merc:alright, fine
> 11:37:55 | MercWMouth:See? Problem solved.
> 11:38:04 | MercWMouth:Nah, man. Merc just said it. He'll stop using AVI.
> 11:38:07 | merc:I will.
> 11:38:11 | MercWMouth:there you go

**Comment by RealDolos** [comment]
MercWMouth... Spammers love him!

> 12:40:09 | MercWMouth:COK: honestly, I'm willing to take your side at this point.
> 12:40:10 | TheJIDF:Ye
> 12:40:19 | MercWMouth:TheJIDF: Well by all means cowboy.
> 12:40:28 | MercWMouth:TheJIDF: You're really proficient, right?
> 12:40:32 | MercWMouth:TheJIDF: By all means. Clean up.
> 12:40:36 | MercWMouth:TheJIDF: Take charge.
> 12:40:45 | MercWMouth:TheJIDF: Let's see what you can do with your own rea­ldolo­s
> 12:41:29 | MercWMouth:TheJIDF: cmon, cmon...!
> 12:41:32 | MercWMouth:You going to take that from him?
> 12:41:35 | MercWMouth:Show him whose boss!
> 12:41:52 | MercWMouth:TheJIDF: Don't be a pussy!
> 12:41:55 | MercWMouth:BAN HIM ALREADY!
> 12:42:12 | MercWMouth:TheJIDF: YOU CAN DO IT!
> 12:42:12 | COK:lol
> 12:42:14 | MercWMouth:I BELIEVE IN YOU!
> 12:42:18 | COK:MercWMouth you are best

**Comment by RealDolos** [comment]
![mercwmouth sides with the spammer 2016-04-28_054922](https://cloud.githubusercontent.com/assets/9981466/14883759/55c7f0e4-0d40-11e6-8204-267d571ef590.png)

@laino like... serious... like... wat

**Comment by RealDolos** [comment]
> MercWMouth:TheJIDF: Go back to school, you flaming idiot.

**Comment by RealDolos** [comment]
This the dude murc keeps unbanning btw:

> 13:01:38 | Macaria:ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN!
> 13:01:39 | Macaria:ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN!
> 13:01:39 | Macaria:ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN! ROCKFELLER WILL RISE AGAIN!

**Comment by RealDolos** [comment]
> 13:14:03 | MercWMouth:hmm. i can practically feel my hair growing out.
> 13:14:11 | MercWMouth:and... is my chest getting hairier?
> 13:14:13 | MercWMouth:0_o;
> 13:14:27 | MercWMouth:MY FEET ARE TRYING TO MOONWALK!
> 13:14:36 | Hydros:bird bird bird
> 13:14:40 | Hydros:bird is the word

**Comment by ghost** [comment]
sup

**Comment by dongmaster** [comment]
> This the dude murc keeps unbanning btw:

That's correct but not really.
He unbanned that dude in that room 3 times and the last unban was 15 hours ago.

Merc is still terrible though.

**Comment by dongmaster** [comment]
> 13:31:00 | MercWMouth: no, i understand. but, look, advertising the stuff just isn't goint to work

So, it was ok earlier but now it's not? (Referring to the dude that was spamming)

**Comment by ghost** [comment]
https://volafile.io/get/80FJP3Npw657fQ/newfag%20emulator.exe

**Comment by dongmaster** [comment]
![merc](https://cloud.githubusercontent.com/assets/6408948/14885962/8eca3fba-0d4e-11e6-8f4f-370883e3bb9e.png)

Here's a staff member talking to himself.

**Comment by RealDolos** [comment]
22:09:59 | MercWMouth:cool. ah, and to make things easier,
22:10:03 | MercWMouth:I'll ban realdolos for you.
22:11:00 | MercWMouth:5minutes it is.

**Comment by RealDolos** [comment]
22:12:26 | MercWMouth:meh. shortened it to two.
22:12:36 | System:You are muted. This ban expires in 2 minutes 5 seconds. Reason: now now...

**Comment by RealDolos** [comment]
> MercWMouth:As you can see... it becomes harder to remind myself to NOT ban reaIdolos...
> TheBroChris:Just ask lain for reminders then, MercWMouth, he reminded you real good the last time
> MercWMouth:lol. lain asked me to do it as a favor to him.

Or in conclusion, MercWMouth does not consider @laino to be in charge, MercWMouth will only and only rarely do favors if he feels like it.

**Comment by FilthyLiquid** [comment]
MercWMouth is continuously joining my room for no reason and shitting it up and causing drama, please do something. (also fix the servers by deleting renegade)

**Comment by RealDolos** [comment]
Murc appears in the peri room, first thing he says:

> MercWMouth:you get your toy back in 10minutes.

Bans bot for no reason.

The murc re-appears:

> MercWMouth:lmmortal: say the word and i mute rea­ldo­los. for real this time because i'm in a really bad mood.
> System:You are muted. This ban expires in 5 minutes 48 seconds. Reason: fuck off

**Comment by FilthyLiquid** [comment]
Please take note this has gone on for 2 days now, it's getting absurd. He's also just straight up abusing users too.
![screenshot-volafile io 2016-04-29 07-59-34](https://cloud.githubusercontent.com/assets/11634496/14909897/7900417e-0de0-11e6-9bf2-f41de1fb9cdb.png)

**Comment by NestorVola** [comment]
Hey guys, so how have things been since I left?  Peachy keen?

**Comment by RealDolos** [comment]
@NestorVola <3
Also, very peachy, yes

**Comment by RealDolos** [comment]
> Deadpool:perici: Re­aldol­os is an aging pedophile.

**Comment by Robertcop** [comment]
all of this and then some

**Comment by Robertcop** [comment]
pls kill merc
