### ISSUE TITLE
Death threat

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#147]
I am used to murc talking shit (who isn't)... but this...

> MercWMouth: I ask because I want to tear his throat out.

Happened in a room I wasn't even in when it happened. From anybody else, I'd just laugh it off as "hurr durr", but murc has a history of meaning these things, seriously and literally, having demonstrated his lack of nuance and ability to understand jokes time and time again, and furthermore he tried to kill a hobo once so he has bloodlust in his mind already.

Please protect me from death threads and violence!

**Comment by NestorVola** [comment]
Threats of violence over the internet are illegal in Germany.  If you have such concerns, you shouldn't be posting them as a bug report, you should be reporting them to the police.  The contact information you will need to provide to the police is available in the Impressum section of any German website, for Volafile, that is at https://volafile.io/impressum.  Obviously there is no promise that the offender will be punished, as he likely resides outside Germany, as a staff member of Volafile, it is Volafile's responsibility to ensure he is not threatening to rip your throat out.
