### ISSUE TITLE
Another day, another modabuse 

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#150]
> RealDolos:KakKakken seems to have a booboo
> RealDolos:Actually, I think murc just hellbanned it...
> RealDolos::check
> RealDolos:yup
> MercWMouth:Re­alBa­nBot v1.0
> RealDolos:see
> MercWMouth:Amazing what $50 will buy you now a days.
> RealArke:WE NEEDZ IT

Also, the The Best Mod Ever started talking to himself again.

**Comment by Robertcop** [comment]
he is truly the bestest mod. #liqudformod #robocop4mod

yes im serious
