### ISSUE TITLE
Please create an overview page of bad words

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#157]
MercWMouth just hellbanned me for using the word "Ian" like 12h ago...
I did not know "Ian" is such a bad word or rather name. All those Ian's worldwide must be furious.

Anyway, in order to avoid using bad words such as "Ian", please create an overview page of these words so I can avoid them!

Kindest, most warmest, most heartfelt regards
Sincerely
Dolos, the Real

**Comment by RealDolos** [comment]
> Reason: get davinci's permission, and you can clamor it all you want

What does this even mean?

**Comment by RealDolos** [comment]
To clarify, if our dear friend the user with the name NiGeR**_iAn**_ is online, am I supposed to call him only NiGeR without the **_iAn**_?

**Comment by dongmaster** [comment]
Yes.

**Comment by RealDolos** [comment]
tonks for the clarification!

**Comment by RealDolos** [comment]
> You are muted. This ban expires in 58 minutes 20 seconds.

**Comment by RealDolos** [comment]
> Reason: got another actual complaint. just give the bastard his space.

wat

**Comment by Robertcop** [comment]
all of my what. this needs to end or be curtailed by a pnishment from head maid, thats you lain

**Comment by RealDolos** [comment]
Pls ban user GNUDoob**\* for using the bad word in his name!

**Comment by RealDolos** [comment]
Apparently saying NotIan is bad too or something?
![dad - a massive handicapped *** for mod ***](https://cloud.githubusercontent.com/assets/9981466/18807998/1b4af69c-8256-11e6-984a-d12387b7ea0a.jpg)
