### ISSUE TITLE
MercWMouth is still abusing people.

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#158]
He banned CaMaDdIcT two times, each for 6 minutes (for no good reason).
His reasoning was "it's for the poor bastard's own good...".

I do not feel that this kind of nanny state bullshit is tolerable.

When's he gonna be demodded?

**Comment by RealDolos** [comment]
> When's he gonna be demodded?

When we reach the 1337 "demod merc" issues filed milestone

**Comment by Robertcop** [comment]
i hope soon. i mean how can you let this happen? i know you like him lain but he gets away with a terrible attitude towards the user base and brings nothing good. maybe a little moding but then he acts poorly. which is a slap in a the face to the site and to your repuation. i mean it's not a good rep lain but still,  you enjoy making it worse?
