### ISSUE TITLE
Room Owners should be able to issue temporary bans from Chat / Filebin

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#166]
Spam is becoming an every day occurance and sometimes hours go by where no staff are online to sort the problem out. Multiple rooms are spammed at once with files and illegal links.

**What I propose:**
Room Owners having the ability to place bans on users (up to 6 hours) for either chatting, uploading or both. IP Addresses and the such should remain hidden from any sort of view.

This would lower the amount of reports that staff get and give room owners a little bit more control over their room.

**Comment by PeterPenesia** [comment]
I approve of this message and the idea.

**Comment by Suntouch** [comment]
I dig the idea and feel it should be implemented.

**Comment by dglans** [comment]
The less white names the better. Hell I'd like invite only but I know that'll never happen.

**Comment by topoff2002** [comment]
This is a good first step.  Hopefully we can take bigger steps in the future such as banning all whites from doing anything in the room (chatting, uploading, downloading) until they register.  So sick of the spam bullshit from them but doing something, like Heisenb3rg suggests, is better than doing nothing.

**Comment by Syrennil** [comment]
I agree. Preferably, it would be a combination of a temp ban, and if the acts repeat, a perm-ban after say three strikes. A reduction in spam, not relying on userscripts to just remove them from the naked eye would reduce the annoyances, and the hazzle the mods experience.

**Comment by barkybarky** [comment]
I also think a room owner should be able to nominate one or two other (perhaps paid) users to act as a room supervisor with the ability to issue temp bans and to delete files 

it would also be nice to have green-only (upping & posting - whites can view and download but nothing else) rooms or invite-only rooms

**Comment by phewwwww** [comment]
Agreed - this should be a feature. It's outta control. I like the "3 strikes" idea. Of course, resilient trolls will always find workarounds to bans (even IP bans) but it's a start and it send a message.

I'd also LOVE a way to mute specific users or mute whites from a chat.

Thanks for your work!

**Comment by EffEff-US** [comment]
This is a great suggestion.  At the very least, a temporary ban would alleviate certain room issues at the start its persistent infraction.  Time and time again, trolls and dissenters cause havoc and downgrades the sanctity of the rooms.  In all fairness to the mods, they can't be available 24/7.  The function would at least provide a temporary solution until a mod can investigate it.

A greens only room is very attractive, but let's face it, we were all white at some point.  A better suggestion might be a whites=[observer only] component.  Muting is another great suggestion along with an appointed assistant room owner.  However, one step at a time.  The ability to impose a ban of some type is good enough to start!

**Comment by barkybarky** [comment]
A current problem that could be fixed right now is the banning of CamGirlVideo caps. There is a user who adds no original content, yet floods the room with auto-caps from camgirlvideos.org. 

Well, what's wrong with that, you might ask. What this is doing, is it's attracting a lot of users who are simply leeching free content from CGV on Vola's bandwidth nickel. And Lain and every user who has donated is paying for that. I don't think the purpose of this room is to act as a free portal for content that, for the most part, is public shows and is auto-capped. 

Banning CGV vids would likely help with the ongoing bandwidth usage, plus, it would probably lower the number of people in the room. The room would almost certainly return to something resembling the very early days when there were maybe 100 or so people in the room who were more focused on sharing interesting stuff. 

Just my 2 cents.

**Comment by phewwwww** [comment]
Maybe a little absolute and labor intensive for mods to implement, but I agree _somewhat_ 

It's nice to see original, current content, but - as a Yankee with no means of procuring a premium Upstore account - I also like having access to retired models whose caps I lost in exhd crash. And to seeing shows I missed or finding out about models - retired and current - who I was unaware of.

Maybe a compromise? Like encouraging ppl to Mega mass dumps of cgv/archive stuff, or discouraging posts of 2nd hand material?

Whatever, I'm happy having Vengeance as a resource, and can't imagine trying to have a life and moderate at the same time. I would like to see more ppl capping. I realize part of the issue is just leeches and laziness, but I know that some ppl really just have no idea how to cap. To assist in the latter case, I wrote a luddite-friendly tutorial, packed in a zip file. I'll try to keep it always up on LEARNTORECORD, so please feel free to direct ppl there.

-pheww

**Comment by Heisenb3rgx** [comment]
@barkybarky That's an issue that has to be taken up with me as it's room specific and not vola-wide. I know who you are talking about however.

The point of this thread was to try and stop spamming by giving room owners the ability to ban users temporarily.

**Comment by barkybarky** [comment]
yes, I know, Heisenb3rg, I just didn't want to bring it up in public chat. 

From what I can see, though, CGV is a bane to the room. While there may be occasional gems on the site, the vast majority of it is shit. And continuing to allow CGV vids is just enabling a lot of leechers to take advantage of vola's [not]free bandwidth and the good intentions of a few members. Which is not at all what the room is about. It is not a clearing house for shit vids for leechers. 

So I don't know how else to deal with that. Anyone have any other ideas? 

--edit--
Maybe tell the guilty party to fulfill only 5 or 10 requests per day. That would certainly cut down on a lot of bandwidth right off the bat...

**Comment by Heisenb3rgx** [comment]
@barkybarky Had a word, it shouldn't be such an issue now. 

On another note, the spammers are back daily (in chat and filebin), which is even more reason why room owners need to have the option to ban. In off hours, there are no staff available, so this would make sense.

**Comment by ghost** [comment]
Yes please. I mod a room with average 200 people in it and the amount of file and chat spam we get from trolls is unbearable. Just in the last hour I've deleted a few hundred files from trolls who know I can't ban or block them so they just keep uploading 

Edit: maybe the ability to have more than one 'room owner' would at least help with moderation of it. If you could have a room owner and other people who can also delete files to keep it clean that'd at least be something

**Comment by laino** [comment]
Room owners can now "timeout" users for up to 15 minutes. This timeout affects both chatting and uploading files.

I'll increase those 15 minutes to something else once I've given room owners the ability to lift timeouts too - currently you need a mod for that.

**Comment by Heisenb3rgx** [comment]
ty bb laino
