### ISSUE TITLE
MercWMouth does joke bans/mutes again

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#168]
> You are muted. This ban expires in 9 seconds. Reason: go outdoors

**Comment by TheJIDF** [comment]
This is outrageous. Something has to be done.

**Comment by redrifle** [comment]
Agreed, 9 seconds is not enough time for outdoor activities.

**Comment by laino** [comment]
I have added the following paragraph to the moderation guidebook (putting us across another page boundary and getting us to 447 pages):

> Section 3, Bans 3.4, Health Related Bans 3.4.17, Outdoor Activies 3.4.17.31
> Bans encouraging the user to partake in outdoor activities shall be at least 3 hours, 
> enough to allow said user to buy groceries and/or go to the movies or visit relatives/friends.
