### ISSUE TITLE
Fight file spam!

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#169]
There is tons of file spam in the recent months, which is rather annoying and our resident spam monkey @dongmaster does not catch it all all the time (well, almost never)

So dear @laino please do some kind of spam filter. Proposed heuristics
- File is (short) .txt or .url file
- File gets uploaded to multiple rooms (>2) in a short time span
- File contains something URL-like (spammer cannot make it too complicated/obfuscated or people won't get it)

Should be easy enough:
- Just cache data about the last files matching the basic criteria for each room
- If a new file matching that criteria gets uploaded, check against previous matched files still cached
- If dupe, take action

Where action could be one of:
- Kill files
- Kill files and spammer
- Auto-report
- Send an email to MercWMouth, explaining why most vola users will vote Trump because of file spam!

**Comment by Heisenb3rgx** [comment]
.url should be a banned extension

Server should detect dupe filenames and auto-delete

**Comment by dongmaster** [comment]
> our resident spam monkey @dongmaster does not catch it all all the time (well, almost never)

I delete quite a few of those spam files. I've contacted Lain about this earlier by the way.

**Comment by RealDolos** [comment]
Yes, you catch a lot @dongmaster, but never all

**Comment by RealDolos** [comment]
Dear @laino,
the spammer now switched to spamming literal CP links

**Comment by RealDolos** [comment]
Related:

> 10:41:00|ReALdoLosiAn:!asleep
> 10:41:00|KakKakken:Mods are asleep

**Comment by Robertcop** [comment]
get the spam monkey!!!

**Comment by Heisenb3rgx** [comment]
Spam is continuing to be a daily occurance. 

MercWMouth was called for one instance in Vengeance last night and did not remove the spam. Terrible.

**Comment by RealDolos** [comment]
@Heisenb3rgx MercWMouth is basically useless, but @laino does not believe us whenever we tell him
