### ISSUE TITLE
Specific Spam in Chat

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#170]
Continiously each day there are users that are spamming a series of money generating links into the chat and it's getting very tiring to keep reporting them (and I'm sure staff are bored of the reports) because as soon as they're banned, they're back.

@laino 
Could you please consider one of the following please? It's getting very out of hand.

A) Letting room owners have chat/bin banning power (IP's can remain hidden)
B) A chat filter which is part of Room Settings that applies to everybody that is in the room (ex; putting linkshrink.net would filter to nothing or *********** )
C) Let Staff control a global filter that filters out annoying urls

**Comment by EffEff-US** [comment]
...or completely deny linkshrink.net or other offending domains.
