### ISSUE TITLE
MercWMouth steals rooms again

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#171]
Dearest @laino, he who has unmatched sexual prowess,

Ollaht does not want Wallander in his room (/v/) and constantly timeout that user.
Now, MercWMouth instead of helping or at least not interfering with the room owner's wishes, untimedouted Wallander and took the room ownership from Ollaht (transferred it to Dongmaster) so he could not issue further timeouts.

MercWMouth was repeatedly told by the room owner, mods like TheJIDF and Dongmaster, and other people to stop this abuse.

Additionally, MercWMouth was told to leave the room, which he refused to do so as well.

**Comment by laino** [comment]
Transferring room ownership or lifting timeouts against the room owner's wishes: THIS IS NOT OKAY AND I'M TRIGGERED. OKAY?

Asking a mod to leave a room: meh, good luck with that.
