### ISSUE TITLE
#triggued LITERALLY BROWN HITLER is triggued

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#173]
>This ban expires in 17 minutes 57 seconds. Reason: The prerogative realdolos himself pointed out as an apt and proper reason.

:cry:

**Comment by RealDolos** [comment]
> Reason: DavidBowie: one of the nice things about there being a lot more moderators now? I can ban you as often as I used to without feeling bad about it since somebody will unban you of pity in a few moments.

**Comment by laino** [comment]
This has been solved to everyone's satisfaction by making @RealDolos a staffer.
Now MercWMouth can keep banning RealDolos without other mods having to go through the trouble of unbanning him all the time.
