### ISSUE TITLE
Implement a spam filter

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#176]
I'm sick and tired of this retarded spam that goes on every fucking day.

Scan every small file for any kind of link shortening URL and allow moderators to block domains in the chat (to prevent clickable links. Only remove links, not actual messages).

Please implement this before you implement any other features because Volafile is spammed literally every day.

**Comment by dongmaster** [comment]
Domains that should be blacklsited:
adf.ly
ouo.io
q.gs
join-adf.ly
viid.me

Update 2016-11-29:  
bit.ly
linkshrink.net
cutt.us
ipbb.ru

Update 2016-12-10:
xvdo.mobi
xbase.ru
hyperboards.com
0pk.ru
akk.li
forum.com.kz

Update 2016-12-21:
situs.ninja

Update 2017-04-12:
9nl.at
io.ua

**Comment by Heisenb3rgx** [comment]
Agreed, this is extremely annoying and it's always the same people doing it. I think a global filter should be implemented as well as a room-specific filter (set by owners) to remove other spam. 

This would personally solve many a lot of spam problems in the bigger rooms.

**Comment by dongmaster** [comment]
The spam is getting worse now.

**Comment by laino** [comment]
done

**Comment by Heisenb3rgx** [comment]
Some additions

goo.gl
ryver.com
gg.gg
uskip.me
xobor.de
unsee.cc
cpc.cx
listav.net
pen.io
link.tl
netxid.com
v.ht
sunda.mobi
cur.lv
