### ISSUE TITLE
Implement draft-ietf-9000-make-vola-great-again-16 (SPAMITY)

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#177]
Room owners of the most popular rooms such as ASMR and Vengeance constantly suffer from targeted spam produced by trolls.

The following steps should rectify this:
1. Allow owners to specify only registered nicks may upload and/or talk (impersonation, evading filters)
2. Allow owners to timeout not just by IP, but also by nick (iphoping)
3. Harden registration flood protection as/if required, e.g. by captcha or validated email, or just by obfuscation and/or minor delays (evading filters, iphoping)
4. Allow owners to permanently ban certain nicks

Each suggestion is worth implementing in itself, but the first 3 would really make this class of spam unreasonably hard and would therefore discourage most, if not all spammers.
Each suggestion is also reasonably easy to implement (eg. 2. could probably just reuse much of the "room disabled" code that still allows mods to post).

As a bonus, it would probably also hamper general, untargeted spam a bit.

Ofc, this would also greatly raise the power by room owners, but then again, people are not required to use the room of some abusive cuck.
There is also a slight chance that somebody will try to DoS vola by creating tons of rooms and adding tons of nicks to the peristent ban list. However, there are already tons of easier ways to DoS vola, and this type of DoS could be also easily mitigated by clamping the number of permanent bans a room owner may perform.

Dear @laino, pls do not make vola the next email!

cc @Heisenb3rgx , @dongmaster 
ref #176 #169

**Comment by Robertcop** [comment]
please work on this

**Comment by ghost** [comment]
I'm Commander Shepard and this is my favorite Issue on the gitadel

**Comment by Heisenb3rgx** [comment]
**As I literally write this, I'm dealing with spam, both of the targetted kind and automated.**

To counter spam, the following could also be implemented for room owners:

**A File Filter** (with white/blacklists)
For example, .txt could be banned, if it contained a certain word in the title, it would be allowed

**Chat Filter**
Filter specific keywords or phrases to "xxxxxx" or simply remove the word altogether. This would be great for spam links in chat.

**No Greeks**
Disable the use of Auto-Generated names in rooms. I'm not saying remove unregistered users, just make it so they HAVE to enter a username.

We also need more than 3 mods that actually do things on a daily basis. There are large gaps of time where nobody is around @laino

**Comment by RealDolos** [comment]
@Heisenb3rgx regarding mods, see #149 #152 #162
