### ISSUE TITLE
404 https://volafile.io/r/BEEPi

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#179]
what WAT

**Comment by RealDolos** [comment]
@laino did you do some DoS protection thingie maybe that does not agree with me having tons of vola tabs?

**Comment by laino** [comment]
if vola thinks you're trying to brute-force rooms it'll start feeding you bs

**Comment by RealDolos** [comment]
Vola should think better, I did not, just connected to a few existing ones

**Comment by laino** [comment]
Yeah, but because of the reset people starting doing connections to rooms that vola didn't know anymore, so vola thought they were just trying random URLs.
