### ISSUE TITLE
Suggestion: clicking on name adds in @[their name] to the chatbox (/w code submission)

### ISSUE THREAD

**Issue by dotheneedful** [Volafile/volafile-bugs#18]
I recently submitted a suggestion to highlight @name messages which was accepted. Now that this is done and using @ is more meaningful, the following might be a good idea: 

If you click on a persons name, put @[name] at the start of your chat box

example code (tested on chrome/ff):

```
$(".message b").click(function(){
    $("#chat_input").focus().removeClass("defaultValue").val("@" + $(this).html() + $("#chat_input").val());
}).css("cursor", "pointer");
```

**Comment by laino** [comment]
we have tab completion now: https://github.com/Volafile/volafile-bugs/issues/26
