### ISSUE TITLE
Requests from Tor to static.volafile.net get a 403 error from cloudflare

### ISSUE THREAD

**Issue by glassbug** [Volafile/volafile-bugs#181]
Since yesterday, when I try to connect to volafile through Tor, I get a 403 error from cloudflare (and their captcha) for all requests to static.volafile.net. See attachment.
![vola_cf_403](https://cloud.githubusercontent.com/assets/24506186/21079993/832c8afa-bf9b-11e6-8ba5-095746d8e488.jpg)

**Comment by laino** [comment]
CloudFlare thinks you're a bad guy

**Comment by laino** [comment]
changed some settings. It might work now. It might not.

**Comment by glassbug** [comment]
Thanks, it seems it works back as normal.
