### ISSUE TITLE
Play short/tiny videos (aka 4chin webms) directly in gallery

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#184]
Tons of stuff that gets posted is meme-tier small videos, small as in length and duration.
Not using gallery for those, but opening them in a new tab is bad UX.

Affected should be:
- Video is of mp4 or webm
- Video is less than 5mins
- Video is max 720p
- File size?

Same holds true for large videos, too. Vola is not fast enough to stream those anyway, so letting them open in the browser player in a new tab instead of going directly to download is just as bad UX wise. Not only does it not play, it's hard for tard users to figure out how to download these.

**Comment by laino** [comment]
halfway there with animated gifs already being converted to videos
