### ISSUE TITLE
MercWMouth refuses to delete reported child pornography

### ISSUE THREAD

**Issue by FilthyLiquid** [Volafile/volafile-bugs#186]
![screenshot-volafile io-2016-12-27-15-53-08](https://cloud.githubusercontent.com/assets/11634496/21503152/051bcb3a-cc4d-11e6-87e6-cf1b51e26817.png)

The files in question are:
The princess.rar
IMG_3405.JPG
IMG_3404.JPG
IMG_3403.JPG

They are in the big Periscope room. 

I reported the files nearly an hour ago. The video/pictures in question are of a girl of 15 years of age. 
They were posted in one of the Swedish/Danish/Norwegian rooms a couple of weeks ago. I know she is underage because someone linked an article, it made the major news in their Country for some reason.

I don't have the article, but it was one of the regular BEEPi users who reported it and linked the article a couple of weeks ago, maybe one of the mods who deleted it last time can remember.

**Comment by bastardsandcheats** [comment]
an hour ago... I reported files which sat for days before being deleted.

Mods don't mod, deal with it
