### ISSUE TITLE
Bot Class & Classed Staff Chat Suggestions

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#187]
1. Add a new class so that bots can bypass flood. Good for the new trivia addition. Won't be abused as regular users can't flood. Also it should be yellow and only assigned by @laino (only 3 people use bots, so it wouldn't be annoying to add them) @RealDolos approves this too.

http://i.imgur.com/B0Mh144.jpg

2. Put a css class on Staff Chat so that it can be coloured and visibly separated from regular chat (everybody wants this)

3. Extend volapro. It's basically dead for everyone.

Also, MercWMouth just logged off because he saw a load of reports and didn't want to deal with them. Terrible.

**Comment by RealDolos** [comment]
:eggplant:

**Comment by Heisenb3rgx** [comment]
@laino pls hurry

**Comment by Robertcop** [comment]
yes lain pls

**Comment by Mist3rl0** [comment]
Point 1 and 2 are necessary and urgent.

**Comment by Heisenb3rgx** [comment]
agree @Robertcop :D
