### ISSUE TITLE
;_;

### ISSUE THREAD

**Issue by AcidV** [Volafile/volafile-bugs#190]
[please do not leave your complaints here]

**Comment by Mist3rl0** [comment]
I am a user of "argentinas amateur" and I can say that the order and the tranquility have been maintained in the last months. Not understanding the reason for the closure of our room.

**Comment by Cabeleira1** [comment]
hi i am cabeleira in argentinian amateur, and i dont undestand why close this room, i am complied the rules and my friend too, if you enable it again iam sure we do our best to make everyone else do it too whit acid

**Comment by laino** [comment]
This is not a place for complaints
