### ISSUE TITLE
speed fix; Add Socket.io P2P as a download method to distribute the content

### ISSUE THREAD

**Issue by Robertcop** [Volafile/volafile-bugs#191]
Add Socket.io P2P to distribute the content in a P2P fashion in order to lower the load on the Volafile servers. Use the original link to the Volafile as a webseed in a superseed mode and let the users exchange the chunks between each other.

This is very similar to torrents and the users' IPs will be visible, but that's the case also with torrents, so some caution has to be practiced. There should be an option to download only from the Volafile server directly to allow for more anonymous downloads.
this was a contribution by MoDChatbot.

**Comment by NestorVola** [comment]
I just got a new job at the MPAA and think this would be a fantastic idea.  Lain please implement.

**Comment by ghost** [comment]
Agree! Actually vola is slow as f*** to download or to upload files.

**Comment by laino** [comment]
We have faster server now
