### ISSUE TITLE
Chat Filter (suggestion)

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#192]
The following image visually explains how a chat filter could be displayed and work on Volafile. 

The feature would also help reduce the number of reports and give room owners the ability to prevent spam links/other spam within their rooms. To prevent abuse, maybe singular words cannot be used, like "the".

![volafile chat filter](https://cloud.githubusercontent.com/assets/22257759/23524154/5aee1934-ff81-11e6-9eb6-bd1d200f2cb2.jpg)

**Comment by Heisenb3rgx** [comment]
@laino

**Comment by Robertcop** [comment]
what a great comment

**Comment by Heisenb3rgx** [comment]
![to fight this](https://cloud.githubusercontent.com/assets/22257759/23596765/86d49b1c-0225-11e7-982a-9b63154a3762.jpg)
 come on, this shit is getting out of hand

**Comment by potistrump** [comment]
i agree with heisenberg we need to fuck these whites up really good.

**Comment by Heisenb3rgx** [comment]
![zero spam prevention](https://cloud.githubusercontent.com/assets/22257759/24438188/88c6d3ac-143d-11e7-9ed1-3ac680949b62.jpg)
@laino This is from tonight alone. Why does volafile have no chat spam prevention? Timing them out is pointless as they switch IP's anyway, so some sort of filter needs to get implemented. 

Blah.

**Comment by Heisenb3rgx** [comment]
16 instances of CP link spam within the past 2 hours. User was timed out every time. Useless.

Remind me again why we don't have a chat filter?

**Comment by laino** [comment]
We now do.
