### ISSUE TITLE
Room Owners hate him! Man from Germany breaks deletion in a few simple steps!

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#195]
@laino 
I just discovered that the new filebin changes made it so that you cannot use the deletion checkbox made available by @RealDolos in his Room Moderation script (literally an essential script for every room owner/moderator)

Clicking the checkbox no longer Selects a file, but instead opens it.

Edit: @dongmaster  also found out that you cannot copy file names either.

**Comment by laino** [comment]
You can fix your script by consuming the event. If you let it bubble it'll eventually open the file.

```js
evt.stopPropagation();
evt.preventDefault();
```
