### ISSUE TITLE
Rest API not working for changed room URL's

### ISSUE THREAD

**Issue by szero** [Volafile/volafile-bugs#197]
When the (((Vola Pro))) user changes the room name, you can no longer use it in the Rest API.
Example call for retrieving upload key for old BEEPi room (now gentoomen):
```bash
curl -H "Referer: https://volafile.org" -H "Accept: text/values" \
            "https://volafile.org/rest/getUploadKey?room=gentoomen&name=Dude"
```
Returns this:
```
error.code=403
error.message=Invalid room.
error.name=Forbidden
error.info=undefined
```

**Comment by laino** [comment]
the "custom room urls" are just "fake rooms" that get resolved to the real ID internally. Check config.room_id to get the real ID of a custom room. So you still have to use BEEPi.
