### ISSUE TITLE
www.volafile.org doesn't redirect properly

### ISSUE THREAD

**Issue by Robertcop** [Volafile/volafile-bugs#198]
www.volafile.org doesn't redirect properly. thank you for your attntion to this matter

**Comment by RealDolos** [comment]
Actually, that subdomain does not even exist xD

**Comment by RealDolos** [comment]
Also, :hankey: :eggplant:

**Comment by Robertcop** [comment]
fix it please :D

**Comment by laino** [comment]
Thanks. Should work in a few hours.
