### ISSUE TITLE
Adonis has a suggestion. im sure youll think its great!

### ISSUE THREAD

**Issue by Robertcop** [Volafile/volafile-bugs#205]
lain it would be good to allow people to delete their own files if they are under a certain size. It just makes no sense not to allow that, with so many accidental uploads, .nfo, thumbs.db, and fulfilled requests sensible to not allow huge files to be deleted, since it would allow major trolling, but small ones should be fine
there might be some privacy issue or concern or something like that, but 4chan was able to do it (first based on password, then based on IP)\

By Adonis. lain what do you think? good idea no?? it is 🗡

**Comment by laino** [comment]
To do that proper I'd need to put a tracking cookie when using Volafile without being logged in,
which would require me to put one of those retarded cookie disclaimers, because EU politicians are just
as inept as anyone at creating sensible regulations.

**Comment by laino** [comment]
I guess I could put the disclaimer right as you click the download button, but that's still one extra click.
