### ISSUE TITLE
Suggestion: Registered Users Only for Pro-Enabled Rooms

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#206]
Rooms that are pro-enabled (100%) could have access to some new features. They are as follows:

**Registered Only Posting & Uploading:**
- A simple checkbox in the room settings that only allows chat/upload by registered users. If pro runs out, this is automatically toggled off.

I've spoken to a few people who run rooms and they also agree that this would be a good feature to have on volafile. It could help cut down on chat/filebin spam, while at the same time, still allowing all users to download.

**Secondary Room Moderators**
- A field within room settings that allows for an additional user to moderate a room. They would have access to deleting files and timing out users, but not the room settings. If pro runs out, this feature stays, similar to URL changing.

Suggested many times before, but would make more sense as a pro-enabled feature.

-------------------------------------------------------------

Non-related

**Name Banning**
- While users can just make a new account, most do not want to because of their upload stats/username/reputation/friends. I've suggested it before but usernames themselves should be bannable and work with the current ban system.

**Comment by TheJIDF** [comment]
I would like to see this but it will **NEVER** happen. Lain is a **LAZY** and plays games all day.

**Comment by ghost** [comment]
![Mock up of room settings panel](https://i.imgur.com/ahV1xHX.png)

**Comment by Robertcop** [comment]
I would like to see this but it will NEVER happen. Lain is a LAZY and plays games all day.
come on lain i know its hard but you can do it!!
good going hisenberg
