### ISSUE TITLE
If you are using file filters, make gallery scope same as the filter

### ISSUE THREAD

**Issue by szero** [Volafile/volafile-bugs#208]
Current behavior is, when you will chose any filter and click on a file to open gallery and move back and forth, you can see images that are outside of the filter. This is counter-intuitive and gallery should reflect what is inside the filter.

**Comment by laino** [comment]
We used to have that, I just changed it back since it's just a config value.

It can be controlled by ``config.ui_gallery_honor_filter = true|false`` for those wishing to change the behavior with an userscript.
