### ISSUE TITLE
Suggestion: Vola-wide Purge

### ISSUE THREAD

**Issue by Heisenb3rgx** [Volafile/volafile-bugs#211]
@laino 

In the past and currently, there are file spammers that are dropping text files containing banned URL's in literally hundreds of rooms per time. One example user currently doing this is being banned at least 20+ times a day (7 times as of writing this) <-edited 4 times already

These files are not always caught right away and many users are fooled into clicking them because they contain false titles such as "VOLA ROOMS", but instead lead through an ad/malware infested series of pay link websites.

**Suggestion:** Add a new feature that allows every single file uploaded by an IP to be removed site-wide. 

@dongmaster @thejidf @robertcop @realdolos

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
Just DDOS the IP's used by the spammers
![hacker-istock_000012339777small](https://user-images.githubusercontent.com/18727826/29481511-eba8e3f2-844f-11e7-88d6-bcf61c0d5e77.jpg)

**Comment by TheJIDF** [comment]
This would be a great addition but it will never happen.

**Comment by Heisenb3rgx** [comment]
In less than 24 hours (same guy, hundreds of rooms)
![massspam](https://user-images.githubusercontent.com/22257759/29485406-5c048a24-84c9-11e7-95a8-60ee5989f55a.jpg)

**Comment by dongmaster** [comment]
Would be nice if we got that, but I don't think it'll come anytime soon because of technical reasons that lain mentioned a long time ago.

**Comment by szero** [comment]
Make a rule that would read text files if they are like less than 10kB and purge it along with the user if it contains any blacklisted links

**Comment by laino** [comment]
We have tools to combat these kinds of spammers now
