### ISSUE TITLE
fix bans already

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#213]
"caching" ban status is the worst idea ever

**Comment by RealDolos** [comment]
bans have to work immediately

**Comment by RealDolos** [comment]
not seconds later

**Comment by RealDolos** [comment]
because seconds later, the spammers will have spammed...

**Comment by RealDolos** [comment]
10 more messages

**Comment by Heisenb3rgx** [comment]
Upvoting because this is an actual issue @laino

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
Yeah I keep banning these people with trusted user status and nothing happens, system is broken as shit they keep spamming no matter what I do. Pls fix laino-san.

**Comment by Heisenb3rgx** [comment]
Bump @laino

**Comment by laino** [comment]
it's fixed
