### ISSUE TITLE
There's a bug that allows you to remove all files in the file list (CLIENT-SIDE)

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#218]
Web browser: Firefox 56.0.2

Description: When this bug is executed, the div with the #files_content id is removed from the DOM, thus removing all files from the file list.

Reproduction:
1. Enter a room
2. Drag a file from the file list to the chat input
3. Press this key combination on your keyboard: CTRL+SHIFT+Delete

Expected behaviour: The file list should *not* disappear

Actual behaviour: The file list disappears

Notes:
I did not discover this bug. The person who found it wishes to remain anonymous.

**Comment by laino** [comment]
Very much sounds like a browser bug, if it is one at all. Also I couldn't reproduce it in either FF or Chrome.
