### ISSUE TITLE
mods shitposting in HF33Go

### ISSUE THREAD

**Issue by ghost** [Volafile/volafile-bugs#222]
@laino

**Comment by TheJIDF** [comment]
I have been sitting in that room for three hours and have witnessed no shitposting. The only shitposting has been from Ollaht in BEEPi. Even MercWMouth banned him because he knew it was a lie.

**Comment by RealDolos** [comment]
yes, do something about this Ollaht guy who keeps shitposting for no reason. Even the room owners lmmortal and someguy1992 had to complain

**Comment by ghost** [comment]
I tried to solve the problem by paswording the room after somebody gave me ownership
unfortunately it didnt work

**Comment by ghost** [comment]
@laino

**Comment by ghost** [comment]
@laino

**Comment by laino** [comment]
HF33Go was removed
