### ISSUE TITLE
Room Ownership Taken Away 

### ISSUE THREAD

**Issue by ThalloBustaNiggaWithaDoubleCap** [Volafile/volafile-bugs#223]
After I spoke to lain yesterday I was muted, then moderators came and took my room and gave it to random /g/ users while banning me for a longer time. Attempts by robocop to fix the situation were overruled. 
![screenshot 146](https://user-images.githubusercontent.com/18727826/33237019-86030910-d23d-11e7-9110-02d43b6ca03f.png)  

Right after you went to bed 

![screenshot 149](https://user-images.githubusercontent.com/18727826/33237047-4b1ef7ae-d23e-11e7-8395-b1282f8e83bc.png) Room ownership was then taken away and given to thejidf

![screenshot 153](https://user-images.githubusercontent.com/18727826/33237060-9b9c998e-d23e-11e7-8342-b2c823b5a9c6.png) After robocop reversed the room ownership theft realdolos gave it to Immortal 

![screenshot 154](https://user-images.githubusercontent.com/18727826/33237064-c9f33d24-d23e-11e7-9a01-83da98969b4e.png) 

My conversation with robocop during the incident 

When room ownership was restored to me I timed out several raiders from beepi, room ownership was then taken away from me and those timeouts reversed 
![screenshot 156](https://user-images.githubusercontent.com/18727826/33237080-4d831420-d23f-11e7-8403-fba1ded34373.png)
![screenshot 157](https://user-images.githubusercontent.com/18727826/33237081-4d960b16-d23f-11e7-9b50-5fcfe1a7ba1a.png)

![screenshot 158](https://user-images.githubusercontent.com/18727826/33237085-7abdcdd6-d23f-11e7-96a7-361820e6205e.png) 
They stated the exact reason I was attacked several times throughout the raid, not that when kreg says "he can" you told me this not a half hour before 
![screenshot 145](https://user-images.githubusercontent.com/18727826/33237090-9b022a60-d23f-11e7-9edd-9376afdeeb96.png)

Further attempts by other mods to end this charade landed someguy1992 in the room ownership position 
![screenshot 159](https://user-images.githubusercontent.com/18727826/33237103-1582860e-d240-11e7-86cd-9c0fa34da2bc.png)

I was then timed out in my own room by the "new" owner 
![screenshot 160](https://user-images.githubusercontent.com/18727826/33237111-49a2c926-d240-11e7-8099-fa775ea09849.png)

To top it off cyberia, who I have had no end of personal problems with tried to make an issue before this and got shitposting in response 
![screenshot 161](https://user-images.githubusercontent.com/18727826/33237116-95537d5c-d240-11e7-8382-1ef2d5969fb3.png)

![screenshot 162](https://user-images.githubusercontent.com/18727826/33237120-ae77fbdc-d240-11e7-9536-7d6a7465bbb5.png) then jde was made room owner

Kreg then banned dongmasters /v/ bot chen and dolos confirmed that jde would be room owner from now on
![screenshot 163](https://user-images.githubusercontent.com/18727826/33237146-59c68a8a-d241-11e7-874a-a7e1d987b4cf.png)

The sad thing is that I have had to deal with almost this exact situation several times now, though this is by far the most autistic display seen since davinci.

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
![screenshot 164](https://user-images.githubusercontent.com/18727826/33237178-c968ebde-d242-11e7-8b78-6f6eb1b9f2ca.png)

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
Then my room url was changed 
![screenshot 165](https://user-images.githubusercontent.com/18727826/33237179-ee67eaac-d242-11e7-9f82-f1f13195ff4f.png)

**Comment by RealDolos** [comment]
that was cyberia

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
and who gave room ownership to cyberia 
![screenshot 166](https://user-images.githubusercontent.com/18727826/33237193-2564e97e-d243-11e7-9e6a-cc0423ec66d3.png)

**Comment by RealDolos** [comment]
you did

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
![screenshot 167](https://user-images.githubusercontent.com/18727826/33237213-8c19de86-d243-11e7-9c82-f1f4fb246cc4.png)

**Comment by kregatcockdotli** [comment]
Thallo is room owner again and his MOTD is still lame

**Comment by ThalloBustaNiggaWithaDoubleCap** [comment]
Now users are being banned for spam when I said its ok, spam is no longer a global rule its enforced by room

**Comment by kregatcockdotli** [comment]
Clearly spamming, files were deleted and uploader muted

**Comment by Figgliness** [comment]
I find it funny how we rolled all those aesthetic updates out to attract new users but then mods like Kreg and Realdolos and then (((trusted users))) like Auxo and Someguy1992 continually harass and abuse one of the most popular rooms on the site, cutting the user count in half over the course of 3 hours of them spamming the entire room and banning several active regulars for complaining about it.

**Comment by Heisenb3rgx** [comment]
Wow.

**Comment by someguy1992** [comment]
I believe all these screen shots were shooped. I request a live video of this event transpiring.

**Comment by anon3000** [comment]
Lain, I am starting to receive messages from users of your site regarding this type of misbehavior. Please make your staff accountable for their actions, and encourage the use of restraint among the moderation team. This type of conduct hurts all parties involved.
