### ISSUE TITLE
#peri is cancerous to the site

### ISSUE THREAD

**Issue by FilthyLiquid** [Volafile/volafile-bugs#224]
.

**Comment by RealDolos** [comment]
Seriously, stfu Liquid. If you actually have evidence there is illegal content, then you should tell actual mods, not bitch about it in some github ticket. As far as I can tell, the content is gone already, was removed more or less immediately after you started bitching.

**Comment by laino** [comment]
There's a dozen channels to discuss moderation. This is not one of them.
