### ISSUE TITLE
Update reports for text to be explicit about copyright

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#232]
As the number of reports (instead of emails) complaining about copyright/personal rights violations is ever increasing, the report form currently does not seem explicit enough.

Please add another paragraph to the intro, along the lines of [see brackets]:
> [Copyright violations and/or personal rights issues CANNOT be reported using this form.]
> ONLY use this form for TOS violations that [our team] [might] confirm at a glance.
> [Otherwise] contact our specialized staff for content removal[s] and[/or] other request[s] [or issues]. (link)

**Comment by szero** [comment]
Also "Contact our specialized staff for content removal and other request." is not obvious button. Either add "press here" next to it or make it look like upload button.

**Comment by RealDolos** [comment]
```text
Use this for to report OBVIOUS illegal content such as child abuse media, bestiality, etc.

Do NOT use this form to report copyright issues, revenge porn, other personal rights and
legal issues or general support inquiries.
Click here to find out how to contact our specialized staff regarding such matters.
```
