### ISSUE TITLE
Don't overwrite longer period bans with shorter period ones

### ISSUE THREAD

**Issue by szero** [Volafile/volafile-bugs#238]
Pedes usually mix up greyzone stuff with CP and if I want to blacklist stuff properly I have to blacklist grayzone before CP because if I'll do that in reverse order it would lead to basically unbanning the pede with a grayzone ban. Also its impossible to blacklist grayzone and other lower issue files of a user that is banned for higher order stuff already, without reapplying the higher order ban afterwards.

**Comment by Heisenb3rgx** [comment]
@laino bumping this

**Comment by szero** [comment]
![image](https://user-images.githubusercontent.com/15748979/83082675-5e831e80-a084-11ea-9993-12f465928fbe.png)
