### ISSUE TITLE
Implying implicated implications

### ISSUE THREAD

**Issue by RealDolos** [Volafile/volafile-bugs#240]
> * By uploading a file to Volafile and thereby making available all of its contents to every intended or possible recipient you **implicate** that you have permission granted by the _rightsholder_ or _rightsholders_ to do so. You also **implicate** that it is legal to provide said content to those recipients as well as that it is legal for those recipients to view and download those files.

You "implicate" somebody in a crime or a scandal or something bad. Heisen/kr3g and me think it's the wrong word, and there are better words, such as: declare, imply, acknowledge, state.

The entire paragraph is odd.. Not specific enough in some areas, overly specific in other areas, and redundant in some places given the previous points of the ToS.
Here is my crack at it:

>* By uploading a file to our service and thereby making it available to other internet users, you declare that - to the best of your knowledge - you have the legal right  and any necessary permissions by any affected third parties to do so, and you assume legal responsibility for all consequences resulting from uploading and sharing the file.

And I'd further add these:
>* You further declare that you give Volafile permission to store and make available the file on your behalf and discretion, without any explicit or implied monetary or other compensation for either party, and you acknowledge that Volafile will merely act as a service provider on your behalf, and that you're still responsible for the content and its distribution.
>* You may explicitly revoke this permission to Volafile at any time and for any reason, in writing (email, postal), in which case Volafile will remove the file from its systems as soon as possible.

**Comment by NestorVola** [comment]
To be fair, Lain's native language is German.  He's also a moron.

**Comment by RealDolos** [comment]
*East German, @NestorVola pls
