### ISSUE TITLE
Suggestion: Allow room owners to have mod powers their room and the power set the expiry time

### ISSUE THREAD

**Issue by ghost** [Volafile/volafile-bugs#31]
First thing just seems like a common sense thing which would allow room owners a degree of control over their room. They could even be given 'demi-mod' powers, eg mutes and bans that only ban from their room.

As for the expiry time just let them set from 0-24 hours, as I'm sure not all room creators want to leave their files up for 24 hours

**Comment by Heisenb3rgx** [comment]
Room Owners should be able to:

Ban users from the chat/filebin/both
Delete all files a user has uploaded (in one go)
Rename files

This would save a lot of time and cut down on mod tickets.

**Comment by laino** [comment]
maybe I'll let them change file expiry time one day too
