### ISSUE TITLE
Elaborate on the stance of the project as FOSS

### ISSUE THREAD

**Issue by Fuuzetsu** [Volafile/volafile-bugs#43]
It'd be great if the project could be made into a FOSS one. If the copyright holders don't want the project to be FOSS, it'd be great if there was an explanation somewhere (such as in README of this repository) on the reason for this.

Sorry for making an issue for this but the main chat seems to be full of children.

**Comment by Fuuzetsu** [comment]
:thinking:

**Comment by laino** [comment]
;^}
