### ISSUE TITLE
Message Highlighting Inconsistent

### ISSUE THREAD

**Issue by NestorVola** [Volafile/volafile-bugs#49]
Hello Lain,

In certain cases, specifically when a username is part of an email address, the name does not trigger message highlighting.  I have attached an example of this happening.

Love,
Nestor
![bug report](https://f.cloud.github.com/assets/6828962/2303484/f43b6e6e-a1c1-11e3-8a00-7e795f6cbbb3.png)

**Comment by Heisenb3rgx** [comment]
@NestorVola Get Vola Highlight++
