### ISSUE TITLE
/rules and /setrule commands for users and room owners repsectively

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#54]
/rules will display a list of room-specific rules set by the room owner. The command could also provide a link to the site's global rules (which currently doesn't exist, and you should create a page for global rules somewhere that people can read). On a user's first visit to a page with custom rules, the rules could be displayed automatically. This way newcomers know what's up.

/setrule can be used by the owner of a room to set the rules for their room. Creation of a rule by an owner should be considered a form of consent to allow volafile moderators to use their discretion to punish users who violate these rules. 

For example, if I owned the "No Bullies" room, I would want to make a rule that says bullying is not allowed. "/setrule1 No Bullying". If I also wanted to forbid pornography, I would do "/setrule2 No NSFW content". Setting a rule to be blank can delete the rule.

I believe this functionality allows room owners to create unique environments which can facilitate the growth of community-centric rooms (such as the croatian one that was discovered recently), or for specific-purpose rooms (such as "lets all share furry porn, no straight furs allowed"). These commands will work best when (if) room owners are given limited mod powers over their room.

**Comment by Heisenb3rgx** [comment]
MOTD is good but it doesn't have any formatting, so it's an OCD fest ;)
