### ISSUE TITLE
anonymized uploads

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#57]
Allow users to upload files without a name associated. Mods will still be able to see ip and everything (meaning lg will spoil all the fun of this feature anyway >:| ). Regular users however will have no idea who uploaded the file. This is guarunteed to lead to fun™ and good times for everyone.

I'm not going to create a 500 page rant on the philosophy behind why I think this feature is important because I recall already making my case to you about it.

and if any of u say "just change ur name to anon before uploading lol," no numbers anon is a respectable member of this community and i will not have everyone besmirch his good name with their "anonymous" uploads. also ur a faget.

**Comment by laino** [comment]
no
