### ISSUE TITLE
Suggestion: Add a "users online" and "total files served" counters

### ISSUE THREAD

**Issue by aux0** [Volafile/volafile-bugs#62]
_total users online_ should show the number of users that are currently online. This should help with gaining new members because people will see the site isn't dead and that something is obviously going on if 50+ people are online every day.

_total files served_ should also serve as a motivator to join the Volafile community. Just like with the number of users online, people will see that files are being actively shared and will gain interest in joining the community.

**Comment by laino** [comment]
> 50
