### ISSUE TITLE
Provide a link to the rules page within rooms

### ISSUE THREAD

**Issue by anon3000** [Volafile/volafile-bugs#78]
The rules page is very important for new users, and particularly so for new users who come from strange *chans where lots of grey area content are frequently uploaded.

I believe that people who come to volafile from these sites are not inherently bad people, and that we should provide them with the opportunity to not "fail" by <b>showing a link to the rules page from within rooms.</b>

I would hazard a guess that currently the vast majority of new users to volafile never see the front page, which is the only place the rules page is linked to. Instead they are linked directly to a room that was created for them, where their only context for what type of content is allowed to be uploaded comes from the turbonerd who linked them there.

Because they have no idea what the rules are, and you do not have a link to the rules page anywhere they can see it, it is unreasonable to expect them to be able to follow the rules very well.

Please give them a chance to understand what type of content is not acceptible by adding a link to the rules page within rooms.

**Comment by laino** [comment]
done.
