### ISSUE TITLE
Suggestion: Create a database of 'blacklisted' files using md5 hashes 

### ISSUE THREAD

**Issue by bbaka** [Volafile/volafile-bugs#83]
Using such a database you could automatically delete illegal files (which have previously been uploaded) and preemptively ban or warn users.

You could also use this as an early warning system of sorts; the system could notify moderators when illegal files are detected and provide a link to the offending file's room.

(Once again the md5 algorithm is merely a suggestion)

**Comment by laino** [comment]
- checksums are implemented
- blacklist is implemented
- blacklisted files trigger automatic reports
