### ISSUE TITLE
Files in the filebin should show if the uploader is banned.

### ISSUE THREAD

**Issue by dongmaster** [Volafile/volafile-bugs#98]
If a person has been banned, all of his files should have a little box attached to it. If you hover over this little box you can see information about the ban, such as ban length and reason, for example.

I would personally benefit from this feature.

This is obviously a mod-only feature request.

Edit:
Q: Why would this be useful?
A: Consider this scenario:
Mod1 enters a room, bans a user for 48 hours and removes the files that broke the rules. However, Mod1 missed a file that breaks the rules. Mod1 leaves the room.

Mod2 enters the same room as mentioned above and sees the file that Mod1 missed (Remember Mod2 doesn't know that Mod1 has been in this room) and bans the uploader of the file for one (1) hour.

The user now had his ban shortened to one (1) hour. This is a big problem.

**Comment by laino** [comment]
Needs to show blacklist settings of the file too.

**Comment by laino** [comment]
Changing bans to always use the longest ban duration would fix the root problem too. Along with an easier way to lookup bans...
